spring:
  application:
    name: placar-tenis

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:placarDb
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true

server:
  port: 8089
